<h1 class="display-1">Index</h1>
<hr />

<div class="container">

		<table class="table table-dark table-hover">
			<caption>Produtos</caption>
			<thead>
				<tr>
					<th>#</th>
					<th>Produto</th>
					<th>Valor</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->view->dados as $indice => $produto) { ?>
					<tr>
						<td><?= $produto['id'] ?></td>
						<td><?= $produto['descricao'] ?></td>
						<td><?= $produto['preco'] ?></td>
					</tr>
				<?php } ?>
			</tbody>
			
		</table>
	
</div>